# Generated by Django 3.2.4 on 2021-12-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
